// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BS
arma::rowvec BS(double t, arma::vec knots);
RcppExport SEXP _DOVE2_BS(SEXP tSEXP, SEXP knotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type knots(knotsSEXP);
    rcpp_result_gen = Rcpp::wrap(BS(t, knots));
    return rcpp_result_gen;
END_RCPP
}
// newCox
List newCox(arma::vec& beta, arma::vec& gamma, const arma::vec& time, const arma::vec& delta, const arma::mat& X, const arma::vec& W, const arma::vec& S, const arma::vec& knots, double threshold, int maxit);
RcppExport SEXP _DOVE2_newCox(SEXP betaSEXP, SEXP gammaSEXP, SEXP timeSEXP, SEXP deltaSEXP, SEXP XSEXP, SEXP WSEXP, SEXP SSEXP, SEXP knotsSEXP, SEXP thresholdSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(newCox(beta, gamma, time, delta, X, W, S, knots, threshold, maxit));
    return rcpp_result_gen;
END_RCPP
}
// newCox_noX
List newCox_noX(arma::vec& gamma, const arma::vec& time, const arma::vec& delta, const arma::vec& W, const arma::vec& S, const arma::vec& knots, double threshold, int maxit);
RcppExport SEXP _DOVE2_newCox_noX(SEXP gammaSEXP, SEXP timeSEXP, SEXP deltaSEXP, SEXP WSEXP, SEXP SSEXP, SEXP knotsSEXP, SEXP thresholdSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(newCox_noX(gamma, time, delta, W, S, knots, threshold, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DOVE2_BS", (DL_FUNC) &_DOVE2_BS, 2},
    {"_DOVE2_newCox", (DL_FUNC) &_DOVE2_newCox, 10},
    {"_DOVE2_newCox_noX", (DL_FUNC) &_DOVE2_newCox_noX, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_DOVE2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
